package uk.ashleybye.avalon.event;

public enum EventType {
  NONE,
  WINDOW_CLOSE,
  WINDOW_RESIZE,
  KEY_PRESSED,
  KEY_RELEASED,
  KEY_TYPED,
  MOUSE_BUTTON_PRESSED,
  MOUSE_BUTTON_RELEASED,
  MOUSE_MOVED,
  MOUSE_SCROLLED,
}
