package uk.ashleybye.avalon.input;

import static org.lwjgl.glfw.GLFW.*;

public class MouseButtonCodes {
  public static final int
      AVALON_MOUSE_BUTTON_1      = GLFW_MOUSE_BUTTON_1,
      AVALON_MOUSE_BUTTON_2      = GLFW_MOUSE_BUTTON_2,
      AVALON_MOUSE_BUTTON_3      = GLFW_MOUSE_BUTTON_3,
      AVALON_MOUSE_BUTTON_4      = GLFW_MOUSE_BUTTON_4,
      AVALON_MOUSE_BUTTON_5      = GLFW_MOUSE_BUTTON_5,
      AVALON_MOUSE_BUTTON_6      = GLFW_MOUSE_BUTTON_6,
      AVALON_MOUSE_BUTTON_7      = GLFW_MOUSE_BUTTON_7,
      AVALON_MOUSE_BUTTON_8      = GLFW_MOUSE_BUTTON_8,
      AVALON_MOUSE_BUTTON_LAST   = AVALON_MOUSE_BUTTON_8,
      AVALON_MOUSE_BUTTON_LEFT   = AVALON_MOUSE_BUTTON_1,
      AVALON_MOUSE_BUTTON_RIGHT  = AVALON_MOUSE_BUTTON_2,
      AVALON_MOUSE_BUTTON_MIDDLE = AVALON_MOUSE_BUTTON_3;
}
